language: minimal
os: linux
dist: bionic
arch: amd64

services:
    - docker

script:
    - docker build -t dockerfile --build-arg RELEASE=ubuntu18.04 .
    - docker build -t dockerfile --build-arg RELEASE=debian:9 .
