# ----------------------------------------------------------------------------------------------------
# Options / Settings
# ----------------------------------------------------------------------------------------------------
set-option -g default-terminal "screen-256color"
set -g mouse on

# ----------------------------------------------------------------------------------------------------
# Key Bindings
# ----------------------------------------------------------------------------------------------------

# Move around panes with ALT + hjkl
bind-key -n M-k select-pane -U
bind-key -n M-h select-pane -L
bind-key -n M-j select-pane -D
bind-key -n M-l select-pane -R

# Resize panes with Alt + Arrow keys
bind -n M-Left  resize-pane -L 5
bind -n M-Right resize-pane -R 5
bind -n M-Up    resize-pane -U 2
bind -n M-Down  resize-pane -D 2

# ----------------------------------------------------------------------------------------------------
# Theme
# ----------------------------------------------------------------------------------------------------

set -g status-fg colour231
set -g status-fg colour231
set -g status-bg colour234
set -g status-left-length 20
set -g status-left '#[fg=colour16,bg=colour254,bold] #S #[fg=colour254,bg=colour234,nobold]'
set -g status-right '#(eval tmux-airline `tmux display -p "#{client_width}"`)'
set -g status-right-length 150

set -g window-status-format "#[fg=colour244,bg=colour234]#I #[fg=colour240] #[default]#W "
set -g window-status-current-format "#[fg=colour234,bg=colour31]#[fg=colour117,bg=colour31] #I  #[fg=colour231,bold]#W #[fg=colour31,bg=colour234,nobold]"

set -g status-bg colour234
set -g status-left-length 20
set -g status-left '#[fg=colour16,bg=colour254,bold] #S #[fg=colour254,bg=colour234,nobold]'
set -g status-right '#(eval tmux-airline `tmux display -p "#{client_width}"`)'
set -g status-right-length 150

set -g window-status-format "#[fg=colour244,bg=colour234]#I #[fg=colour240] #[default]#W "
set -g window-status-current-format "#[fg=colour234,bg=colour31]#[fg=colour117,bg=colour31] #I  #[fg=colour231,bold]#W #[fg=colour31,bg=colour234,nobold]"
set -g status-right "#[fg=colour234,bg=colour31]#[fg=colour31] #[fg=colour117,bold]%Y-%m-%d %H:%M#[fg=colour31,nobold] #[bg=colour234]#[fg=colour234] #[fg=green]#H"

set -g window-status-style fg=colour249
set -g window-status-activity-style fg=yellow,none
set -g window-status-bell-style fg=red,none
