-- following options are the default
-- each of these are documented in `:help nvim-tree.OPTION_NAME`
require("nvim-tree").setup()

-- NON OF THIS WORKS ......
--
--
--local status_ok, nvim_tree = pcall(require, "nvim-tree")
--if not status_ok then
--  return
--end
--
--local config_status_ok, nvim_tree_config = pcall(require, "nvim-tree.config")
--if not config_status_ok then
--  return
--end
--
--local tree_cb = nvim_tree_config.nvim_tree_callback
--
--nvim_tree.setup {
--  filters = {
--    dotfiles = true,
--    custom = {'.git', 'node_modules', '.cache'}
--  },
--  disable_netrw = true,
--  hijack_netrw = true,
--  open_on_setup = true,
--  open_on_tab = true,
--  ignore_ft_on_setup = {
--    "startify",
--    "dashboard",
--    "alpha",
--  },
--  hijack_cursor = false,
--  update_cwd = true,
--  diagnostics = {
--    enable = true,
--    icons = {
--      hint = "",
--      info = "",
--      warning = "",
--      error = "",
--    },
--  },
--  update_focused_file = {
--    enable = true,
--    update_cwd = true,
--    ignore_list = {},
--  },
--  git = {
--    enable = true,
--    ignore = true,
--    timeout = 500,
--  },
--  view = {
--    width = 40,
--    hide_root_folder = false,
--    side = "left",
--    mappings = {
--      custom_only = false,
--      list = {
--        { key = { "l", "<CR>", "o" }, cb = tree_cb "edit" },
--        { key = "h", cb = tree_cb "close_node" },
--        { key = "v", cb = tree_cb "vsplit" },
--      },
--    },
--    number = false,
--    relativenumber = false,
--  },
--}

-- Auto Close when last buffer
vim.cmd("autocmd BufEnter * ++nested if winnr('$') == 1 && bufname() == 'NvimTree_' . tabpagenr() | quit | endif")
