#!/bin/bash
# ===== Global Settings / Variables =====
set -o nounset   # to cause an error if you use an empty variable
set -o noclobber # the '>' symbol not allowed to overwrite "existing" files
set -o pipefail  # cmd_a | cmd_b . Fails if cmd_a doesn't cleanly exit (0) 


function main() {
    local target_dir
    target_dir="$(readlink -ef $(pwd)/target)"

    # Check if already mounted => exit
    if grep "$target_dir" /proc/mounts >> /dev/null; then
        echo "Target directory ($target_dir) is already mounted as ramdisk"
        exit 0
    fi

    # Remove target directory
    if [[ -d "target" ]]; then
        echo "Cargo cleaning ..."
        cargo clean || (echo "Failed to run cargo clean" && exit 1)
    fi

    echo "Creating ramdisk ..."
    mkdir -p target && \
        sudo mount -t tmpfs none ./target && \
        sudo chown $(whoami):$(whoami) target && \
        echo "Successfully mounted directory $target_dir"
}

main "$@"
